services:
  dev-server:
    profiles:
      - dev
    image: raq-dev:latest
    container_name: raq-dev-server
    volumes:
      - ".:/workdir"
    ports:
      - 8000:8000
    depends_on:
      - influxdb
    command: >
      uvicorn src.raq.server.main:app
        --reload
        --log-level=debug
        --host 0.0.0.0

  grafana:
    profiles:
      - dev
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
     - 3000:3000
    volumes:
    - grafana-storage:/var/lib/grafana
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.

  influxdb:
    profiles:
      - dev
    image: influxdb:latest
    container_name: influxdb2
    volumes:
      - ./influxdb/data:/var/lib/influxdb2:rw
    ports:
      - 8086:8086
    restart: unless-stopped

  server:
    profiles:
      - prod
    image: raq-server:latest
    container_name: raq-server
    network_mode: host
    command: >
      uvicorn src.raq.server.main:app
        --log-level=info
        --host 0.0.0.0
    env_file:
      - server.env

volumes:
  grafana-storage: {}
